Repository dsccommunity/SecurityPolicyDsc, pull requests merged in 2019-03, with the labels that each got.

#112 SecurityOption/AccountPolicy: Add validation attributes to parameters
  DSCResources/MSFT_AccountPolicy/MSFT_AccountPolicy.psm1
  DSCResources/MSFT_SecurityOption/MSFT_SecurityOption.psm1
  DSCResources/MSFT_SecurityOption/MSFT_SecurityOption.schema.mof
  README.md
Labels: needs review

#109 SecurityPolicyDsc: Updated LICENSE file to match the Microsoft Open Source Team standard. Fixes Issue #108
  LICENSE
  README.md
Labels: ready for merge

#93 SecurityPolicyDSC: Add FUTURE as Kerberos Encryption Type. Fixes #66
  DSCResources/MSFT_SecurityOption/MSFT_SecurityOption.psm1
  DSCResources/MSFT_SecurityOption/MSFT_SecurityOption.schema.mof
  DSCResources/MSFT_SecurityOption/SecurityOptionData.psd1
  README.md
  Tests/Unit/MSFT_SecurityOption.tests.ps1
Labels: abandoned, waiting for code fix
